---
# tasks file for maven
- name: Install python
  apt: 
    name: software-properties-common
    state: present

- name: Add maven stable repository from PPA
  apt_repository:
    repo: 'ppa:ts.sch.gr/ppa'

- name: Update Apt Repos
  apt: 
    upgrade: yes
    update_cache: yes

- name: Install Java
  apt:
    name: default-jdk
    state: latest
    update_cache: yes

- name: Make new directory
  file:
    path: /opt/maven
    state: directory
    mode: '0755'

- name: Download maven server packages
  get_url:
    url: https://dlcdn.apache.org/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz
    dest: /opt/maven

- name: Extract maven packages
  unarchive:
    src: /opt/maven/apache-maven-3.8.3-bin.tar.gz
    dest: /opt/maven

- name: Install package
  become: yes
  shell: update-alternatives --install /usr/bin/mvn maven /opt/maven/apache-maven-3.8.3/bin/mvn 1001

